// Category grid data, shared by the home page's "Explore Our Work By Category"
// grid and the contact page's category gallery carousel.
export const CATEGORIES = [
  ["Airbnb", "/uploads/modern-bedroom-white-gloss-wardrobe-wood-slat-accent-wall.webp", ["/assets/gallery/airbnb-01.webp", "/assets/gallery/airbnb-02.webp", "/assets/gallery/airbnb-03.webp", "/assets/gallery/airbnb-04.webp", "/assets/gallery/airbnb-05.webp", "/assets/gallery/airbnb-06.webp", "/assets/gallery/airbnb-07.webp", "/assets/gallery/airbnb-08.webp", "/assets/gallery/airbnb-09.webp"]],
  ["Bathrooms", "/uploads/omar-decor-brass-fittings-bathroom-bath-shower-02.webp", ["/assets/gallery/bathrooms-01.webp", "/assets/gallery/bathrooms-02.webp", "/assets/gallery/bathrooms-03.webp", "/assets/gallery/bathrooms-04.webp", "/assets/gallery/bathrooms-05.webp", "/assets/gallery/bathrooms-06.webp", "/assets/gallery/bathrooms-07.webp", "/assets/gallery/bathrooms-08.webp", "/assets/gallery/bathrooms-09.webp", "/assets/gallery/bathrooms-10.webp", "/assets/gallery/bathrooms-11.webp", "/assets/gallery/bathrooms-12.webp", "/assets/gallery/bathrooms-13.webp", "/assets/gallery/bathrooms-14.webp"]],
  ["Carpentry", "/uploads/omar-decor-white-fitted-storage-unit-oak-flooring.webp", ["/uploads/omar-decor-carpentry-fitted-wardrobe-desk-unit-blue-bedroom-collage.webp", "/uploads/omar-decor-carpentry-fitted-wardrobes-bedroom-chimney-breast-collage.webp", "/uploads/omar-decor-carpentry-fitted-wardrobes-parquet-bedroom-collage.webp", "/uploads/omar-decor-carpentry-living-room-alcove-tv-unit-fitted-shelving-collage.webp", "/uploads/omar-decor-carpentry-media-wall-unit-built-in-shelving-collage.webp", "/uploads/omar-decor-carpentry-tv-unit-sliding-door-cabinet-collage.webp", "/uploads/omar-decor-carpentry-alcove-shelving-cabinet-living-room-collage.webp", "/uploads/omar-decor-carpentry-alcove-shelving-led-lighting-cabinet-collage.webp", "/uploads/omar-decor-carpentry-fitted-media-unit-bedroom-storage-collage.webp", "/uploads/omar-decor-carpentry-fitted-wardrobe-bedroom-installation-collage.webp", "/uploads/omar-decor-carpentry-fitted-wardrobe-desk-tv-unit-bedroom-01-collage.webp", "/uploads/omar-decor-carpentry-fitted-wardrobe-desk-tv-unit-bedroom-02-collage.webp"]],
  ["Commercials", "/uploads/omar-decor-commercial-barber-shop-styling-station-finished.webp", ["/uploads/omar-decor-commercial-barber-shop-haircut-in-progress.webp", "/uploads/omar-decor-commercial-barber-shop-styling-station-finished.webp", "/uploads/omar-decor-commercial-bathroom-kitchenette-fit-out-before-after.webp", "/uploads/omar-decor-commercial-moe-da-barber-studio-fit-out-before-after-01.webp", "/uploads/omar-decor-commercial-moe-da-barber-studio-fit-out-before-after-02.webp", "/uploads/omar-decor-commercial-retail-shop-flooring-installation-before-after.webp"]],
  ["Fashion Studios & Offices", "/uploads/omar-decor-living-room-teal-wall-palm-art-sofas.webp", ["/uploads/omar-decor-fashion-office-reception-fit-out-before-after-02.webp", "/uploads/omar-decor-fashion-office-staircase-feature-wall.webp", "/uploads/omar-decor-fashion-office-teal-feature-wall-fit-out-collage.webp", "/uploads/omar-decor-fashion-office-breakout-lounge-fit-out-collage.webp", "/uploads/omar-decor-fashion-office-creative-studio-office-desk-feature-wall.webp", "/uploads/omar-decor-fashion-office-creative-studio-office-fit-out-before-after-collage.webp", "/uploads/omar-decor-fashion-office-reception-fit-out-before-after-01.webp"]],
  ["Flooring", "/uploads/omar-decor-styled-bedroom-rust-cushions-headboard-01.webp", ["/uploads/omar-decor-flooring-hallway-laminate-flooring-installation-collage.webp", "/uploads/omar-decor-flooring-herringbone-parquet-flooring-kitchen-collage.webp", "/uploads/omar-decor-flooring-honey-oak-laminate-flooring-apartment-collage.webp", "/uploads/omar-decor-flooring-oak-laminate-bedroom-flooring-collage.webp", "/uploads/omar-decor-flooring-oak-laminate-flooring-bay-window-living-room.webp", "/uploads/omar-decor-flooring-oak-laminate-flooring-red-sofa-living-room-collage.webp", "/uploads/omar-decor-flooring-oak-laminate-living-room-flooring-collage.webp", "/uploads/omar-decor-flooring-oak-wood-flooring-living-room-fireplace-collage.webp", "/uploads/omar-decor-flooring-riverside-apartment-wood-flooring-installation.webp", "/uploads/omar-decor-flooring-walnut-laminate-flooring-hallway-collage.webp", "/uploads/omar-decor-flooring-walnut-laminate-flooring-installation-collage.webp", "/uploads/omar-decor-flooring-whitewashed-pine-flooring-bedroom-collage.webp", "/uploads/omar-decor-flooring-artificial-grass-staircase-carpet-collage.webp", "/uploads/omar-decor-flooring-chestnut-wood-flooring-hallway-collage.webp", "/uploads/omar-decor-flooring-grey-oak-flooring-hallway-staircase-collage.webp", "/uploads/omar-decor-flooring-grey-vinyl-staircase-flooring-collage.webp"]],
  ["Full Renovation", "/uploads/omar-decor-full-renovation-cover.webp", ["/uploads/omar-decor-full-renovation-bedroom-kitchen-collage.webp", "/uploads/omar-decor-full-renovation-bedroom-laminate-flooring-collage.webp", "/uploads/omar-decor-full-renovation-bedroom-wardrobe-flooring-collage.webp", "/uploads/omar-decor-full-renovation-herringbone-flooring-collage.webp", "/uploads/omar-decor-full-renovation-kitchen-extension-before-after-collage.webp", "/uploads/omar-decor-full-renovation-living-room-feature-wallpaper-collage.webp", "/uploads/omar-decor-full-renovation-living-room-media-wall-collage.webp", "/uploads/omar-decor-full-renovation-period-property-parquet-flooring.webp", "/uploads/omar-decor-full-renovation-wall-removal-home-cinema-collage.webp"]],
  ["Kitchens", "/uploads/omar-decor-grey-gloss-kitchen-induction-hob-extractor.webp", ["/uploads/omar-decor-kitchen-white-kitchen-installation-progress-collage.webp", "/uploads/omar-decor-kitchen-black-matt-kitchen-led-lighting-collage.webp", "/uploads/omar-decor-kitchen-charcoal-gloss-kitchen-renovation-collage.webp", "/uploads/omar-decor-kitchen-herringbone-tile-kitchen-installation-collage.webp", "/uploads/omar-decor-kitchen-sage-green-kitchen-renovation-collage.webp", "/uploads/omar-decor-kitchen-white-gloss-kitchen-renovation-collage.webp"]],
  ["Painting and Decorating", "/uploads/omar-decor-living-room-teal-feature-wall-clock.webp", ["/uploads/omar-decor-period-property-painting-decorating-collage.webp", "/uploads/omar-decor-painting-decorating-portfolio-grid-collage-01.webp", "/uploads/omar-decor-mustard-wall-damask-wallpaper-renovation-collage.webp", "/uploads/omar-decor-living-room-before-after-collage.webp", "/uploads/omar-decor-kitchen-hallway-painting-collage.webp", "/uploads/omar-decor-hallway-painting-before-after.webp", "/uploads/omar-decor-floral-wallpaper-hallway-collage.webp", "/uploads/omar-decor-bedroom-sage-green-fitted-wardrobe-collage.webp", "/uploads/omar-decor-bedroom-pink-paint-before-after.webp", "/uploads/omar-decor-bedroom-painting-decorating-collage.webp", "/uploads/omar-decor-bedroom-orange-brown-feature-wall-before-after.webp", "/uploads/omar-decor-bedroom-green-feature-wall-before-after.webp", "/uploads/omar-decor-apartment-kitchen-diner-renovation-collage.webp"]],
];

// Figma "Alt (Revised V2)" heading differs from the internal category key
// for Airbnb only; every other card's heading matches its key verbatim.
export const CATEGORY_LABELS = { Airbnb: "Airbnb-Ready Space" };
export const CATEGORY_CAPTIONS = {
  Airbnb: "We help landlords transform their properties into standout short-term rentals that attract more guests and earn more revenue.",
  Bathrooms: "Full bathroom renovations from tiling to plumbing and fixtures.",
  Carpentry: "Custom woodwork, shelving and bespoke joinery for your home.",
  Commercials: "Professional decorating solutions for offices, shops and commercial spaces.",
  "Fashion Studios & Offices": "Tailored interiors for fashion studios, offices and creative workspaces.",
  Flooring: "Professional flooring installation for every room and finish.",
  "Full Renovation": "Complete property renovations managed from planning through final finish.",
  Kitchens: "Complete kitchen transformations designed and built to last.",
  "Painting and Decorating": "Professional painting and decorating with clean, lasting finishes.",
};

export function altFor(name) {
  const room = name.startsWith("kitchen") ? "Kitchen fitting" : name.startsWith("bathroom") ? "Bathroom renovation" : "Flat renovation";
  const place = name.split("-").slice(-2, -1)[0];
  return room + " in " + place.charAt(0).toUpperCase() + place.slice(1) + " by Omar Decor";
}

export const GALLERY_IMG = "/assets/gallery/";
