// Small display variants generated by scripts/make-web-sizes.py. Originals stay
// for the lightboxes; pages show these so they don't download 1500-2000px photos
// into 150-600px boxes.
export const md = (src) => src.replace(/\.webp$/, "-md.webp");
export const sq = (src) => src.replace(/\.webp$/, "-sq.webp");
